# pyaegis.pyi
from __future__ import annotations
from typing import Callable, Literal, Optional, Sequence, Union

# module-level constants
CONTINUE_MSG: int
EXIT_MSG: int
INIT_MSG: int
READ_MSG: int
WRITE_MSG: int

class PyFlagState:
    """
    Represents the CPU flags register state (e.g., EFLAGS/RFLAGS).
    """

    def __init__(self, value: int) -> None: ...
    def __str__(self) -> str: ...
    def compare(self, other: PyFlagState) -> str:
        """
        Compare this flag state with another and return a human-readable diff.
        """
        ...

    @property
    def value(self) -> int: ...

class PyCpuState:
    """
    Represents the full CPU state, including GPRs, segment registers, MMX registers, RIP, and flags.
    """

    def __init__(self) -> None: ...
    def __str__(self) -> str: ...
    def diff(self, other: PyCpuState) -> PyCpuState:
        """
        Compute a diff between this CPU state and another by xoring each register.
        """
        ...
    # MMX registers
    @property
    def mm0(self) -> int: ...
    @mm0.setter
    def mm0(self, v: int) -> None: ...
    @property
    def mm1(self) -> int: ...
    @mm1.setter
    def mm1(self, v: int) -> None: ...
    @property
    def mm2(self) -> int: ...
    @mm2.setter
    def mm2(self, v: int) -> None: ...
    @property
    def mm3(self) -> int: ...
    @mm3.setter
    def mm3(self, v: int) -> None: ...
    @property
    def mm4(self) -> int: ...
    @mm4.setter
    def mm4(self, v: int) -> None: ...
    @property
    def mm5(self) -> int: ...
    @mm5.setter
    def mm5(self, v: int) -> None: ...
    @property
    def mm6(self) -> int: ...
    @mm6.setter
    def mm6(self, v: int) -> None: ...
    @property
    def mm7(self) -> int: ...
    @mm7.setter
    def mm7(self, v: int) -> None: ...

    # GPRs
    @property
    def rax(self) -> int: ...
    @rax.setter
    def rax(self, v: int) -> None: ...
    @property
    def rbx(self) -> int: ...
    @rbx.setter
    def rbx(self, v: int) -> None: ...
    @property
    def rcx(self) -> int: ...
    @rcx.setter
    def rcx(self, v: int) -> None: ...
    @property
    def rdx(self) -> int: ...
    @rdx.setter
    def rdx(self, v: int) -> None: ...
    @property
    def rsi(self) -> int: ...
    @rsi.setter
    def rsi(self, v: int) -> None: ...
    @property
    def rdi(self) -> int: ...
    @rdi.setter
    def rdi(self, v: int) -> None: ...
    @property
    def rbp(self) -> int: ...
    @rbp.setter
    def rbp(self, v: int) -> None: ...
    @property
    def rsp(self) -> int: ...
    @rsp.setter
    def rsp(self, v: int) -> None: ...
    @property
    def r8(self) -> int: ...
    @r8.setter
    def r8(self, v: int) -> None: ...
    @property
    def r9(self) -> int: ...
    @r9.setter
    def r9(self, v: int) -> None: ...
    @property
    def r10(self) -> int: ...
    @r10.setter
    def r10(self, v: int) -> None: ...
    @property
    def r11(self) -> int: ...
    @r11.setter
    def r11(self, v: int) -> None: ...
    @property
    def r12(self) -> int: ...
    @r12.setter
    def r12(self, v: int) -> None: ...
    @property
    def r13(self) -> int: ...
    @r13.setter
    def r13(self, v: int) -> None: ...
    @property
    def r14(self) -> int: ...
    @r14.setter
    def r14(self, v: int) -> None: ...
    @property
    def r15(self) -> int: ...
    @r15.setter
    def r15(self, v: int) -> None: ...

    # RIP
    @property
    def rip(self) -> int: ...
    @rip.setter
    def rip(self, v: int) -> None: ...

    # Segment registers
    @property
    def cs(self) -> int: ...
    @cs.setter
    def cs(self, v: int) -> None: ...
    @property
    def ds(self) -> int: ...
    @ds.setter
    def ds(self, v: int) -> None: ...
    @property
    def es(self) -> int: ...
    @es.setter
    def es(self, v: int) -> None: ...
    @property
    def fs(self) -> int: ...
    @fs.setter
    def fs(self, v: int) -> None: ...
    @property
    def gs(self) -> int: ...
    @gs.setter
    def gs(self, v: int) -> None: ...
    @property
    def ss(self) -> int: ...
    @ss.setter
    def ss(self, v: int) -> None: ...

    # Flags
    @property
    def flags(self) -> PyFlagState: ...
    @flags.setter
    def flags(self, v: int) -> None: ...

class PyNamedTestCase:
    """
    A test case with a unique ID, name, CPU state, and instruction bytes.
    """

    def __init__(
        self, id: int, name: str, state: PyCpuState, insn: Sequence[int]
    ) -> None: ...
    @property
    def name(self) -> str: ...
    @property
    def test_case(self) -> PyTestCase: ...

class PyTestCase:
    """
    Low-level representation of a single test case with ID, CPU state, and instruction bytes.
    """

    def __init__(self, id: int, state: PyCpuState, insn: Sequence[int]) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def state(self) -> PyCpuState: ...
    @property
    def insn(
        self,
    ) -> tuple[
        int, int, int, int, int, int, int, int, int, int, int, int, int, int, int
    ]: ...
    @property
    def size(self) -> int: ...

class PyTest:
    """
    Represents a test run, including the instruction, start and end CPU states.
    """

    def __init__(
        self,
        id: int,
        name: str,
        start_state: PyCpuState,
        end_state: PyCpuState,
        insn: Sequence[int],
    ) -> None: ...
    @property
    def id(self) -> int: ...
    @property
    def name(self) -> str: ...
    @property
    def start_state(self) -> PyCpuState: ...
    @property
    def end_state(self) -> PyCpuState: ...
    @property
    def insn(self) -> list[int]: ...

class PyAegis:
    """
    Main interface to run Aegis tests.

    Args:
        serial_sock: Path to the serial socket used for server communication.
        shared_mem: Path to shared memory (ivshmem) used for client-server communication.
        read: Callback that processes a PyTest result.
        write: Callback that generates a new PyNamedTestCase or "random_8086" mode.
    """

    def __init__(
        self,
        serial_sock: str,
        shared_mem: str,
        read: Callable[[PyTest], None],
        write: Union[
            Callable[[int], Optional[PyNamedTestCase]], Literal["random_8086"]
        ],
    ) -> None: ...
    def run(self) -> None:
        """
        Start the client loop, sending tests to the server and receiving results.
        """
        ...
